// Copyright 2025 Contributors to the Veraison project.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v5.29.3
// source: compositor.proto

package compositor

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result bool   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Error  string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *Status) Reset() {
	*x = Status{}
	if protoimpl.UnsafeEnabled {
		mi := &file_compositor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_compositor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_compositor_proto_rawDescGZIP(), []int{0}
}

func (x *Status) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

func (x *Status) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SubAttesterID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *SubAttesterID) Reset() {
	*x = SubAttesterID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_compositor_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubAttesterID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubAttesterID) ProtoMessage() {}

func (x *SubAttesterID) ProtoReflect() protoreflect.Message {
	mi := &file_compositor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubAttesterID.ProtoReflect.Descriptor instead.
func (*SubAttesterID) Descriptor() ([]byte, []int) {
	return file_compositor_proto_rawDescGZIP(), []int{1}
}

func (x *SubAttesterID) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SubAttesterID) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type SubAttesterIDOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status        *Status        `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	SubAttesterID *SubAttesterID `protobuf:"bytes,2,opt,name=subAttesterID,proto3" json:"subAttesterID,omitempty"`
}

func (x *SubAttesterIDOut) Reset() {
	*x = SubAttesterIDOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_compositor_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubAttesterIDOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubAttesterIDOut) ProtoMessage() {}

func (x *SubAttesterIDOut) ProtoReflect() protoreflect.Message {
	mi := &file_compositor_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubAttesterIDOut.ProtoReflect.Descriptor instead.
func (*SubAttesterIDOut) Descriptor() ([]byte, []int) {
	return file_compositor_proto_rawDescGZIP(), []int{2}
}

func (x *SubAttesterIDOut) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *SubAttesterIDOut) GetSubAttesterID() *SubAttesterID {
	if x != nil {
		return x.SubAttesterID
	}
	return nil
}

type Format struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContentType string `protobuf:"bytes,1,opt,name=contentType,proto3" json:"contentType,omitempty"`
	NonceSize   uint32 `protobuf:"varint,2,opt,name=nonceSize,proto3" json:"nonceSize,omitempty"`
}

func (x *Format) Reset() {
	*x = Format{}
	if protoimpl.UnsafeEnabled {
		mi := &file_compositor_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Format) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Format) ProtoMessage() {}

func (x *Format) ProtoReflect() protoreflect.Message {
	mi := &file_compositor_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Format.ProtoReflect.Descriptor instead.
func (*Format) Descriptor() ([]byte, []int) {
	return file_compositor_proto_rawDescGZIP(), []int{3}
}

func (x *Format) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *Format) GetNonceSize() uint32 {
	if x != nil {
		return x.NonceSize
	}
	return 0
}

type SupportedFormatsOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  *Status   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Formats []*Format `protobuf:"bytes,2,rep,name=formats,proto3" json:"formats,omitempty"`
}

func (x *SupportedFormatsOut) Reset() {
	*x = SupportedFormatsOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_compositor_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SupportedFormatsOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupportedFormatsOut) ProtoMessage() {}

func (x *SupportedFormatsOut) ProtoReflect() protoreflect.Message {
	mi := &file_compositor_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupportedFormatsOut.ProtoReflect.Descriptor instead.
func (*SupportedFormatsOut) Descriptor() ([]byte, []int) {
	return file_compositor_proto_rawDescGZIP(), []int{4}
}

func (x *SupportedFormatsOut) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *SupportedFormatsOut) GetFormats() []*Format {
	if x != nil {
		return x.Formats
	}
	return nil
}

type EvidenceIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContentType string `protobuf:"bytes,1,opt,name=contentType,proto3" json:"contentType,omitempty"`
	Nonce       []byte `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
}

func (x *EvidenceIn) Reset() {
	*x = EvidenceIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_compositor_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EvidenceIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvidenceIn) ProtoMessage() {}

func (x *EvidenceIn) ProtoReflect() protoreflect.Message {
	mi := &file_compositor_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvidenceIn.ProtoReflect.Descriptor instead.
func (*EvidenceIn) Descriptor() ([]byte, []int) {
	return file_compositor_proto_rawDescGZIP(), []int{5}
}

func (x *EvidenceIn) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *EvidenceIn) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

type EvidenceOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status   *Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Evidence []byte  `protobuf:"bytes,2,opt,name=evidence,proto3" json:"evidence,omitempty"`
}

func (x *EvidenceOut) Reset() {
	*x = EvidenceOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_compositor_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EvidenceOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvidenceOut) ProtoMessage() {}

func (x *EvidenceOut) ProtoReflect() protoreflect.Message {
	mi := &file_compositor_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvidenceOut.ProtoReflect.Descriptor instead.
func (*EvidenceOut) Descriptor() ([]byte, []int) {
	return file_compositor_proto_rawDescGZIP(), []int{6}
}

func (x *EvidenceOut) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *EvidenceOut) GetEvidence() []byte {
	if x != nil {
		return x.Evidence
	}
	return nil
}

var File_compositor_proto protoreflect.FileDescriptor

var file_compositor_proto_rawDesc = []byte{
	0x0a, 0x10, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x1a, 0x1b,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x36, 0x0a, 0x06, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x22, 0x3d, 0x0a, 0x0d, 0x53, 0x75, 0x62, 0x41, 0x74, 0x74, 0x65, 0x73, 0x74,
	0x65, 0x72, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x22, 0x7f, 0x0a, 0x10, 0x53, 0x75, 0x62, 0x41, 0x74, 0x74, 0x65, 0x73, 0x74, 0x65,
	0x72, 0x49, 0x44, 0x4f, 0x75, 0x74, 0x12, 0x2a, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x6f, 0x72, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x3f, 0x0a, 0x0d, 0x73, 0x75, 0x62, 0x41, 0x74, 0x74, 0x65, 0x73, 0x74, 0x65,
	0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x63, 0x6f, 0x6d, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x53, 0x75, 0x62, 0x41, 0x74, 0x74, 0x65, 0x73, 0x74,
	0x65, 0x72, 0x49, 0x44, 0x52, 0x0d, 0x73, 0x75, 0x62, 0x41, 0x74, 0x74, 0x65, 0x73, 0x74, 0x65,
	0x72, 0x49, 0x44, 0x22, 0x48, 0x0a, 0x06, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x20, 0x0a,
	0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x09, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x6f, 0x0a,
	0x13, 0x53, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74,
	0x73, 0x4f, 0x75, 0x74, 0x12, 0x2a, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f,
	0x72, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x2c, 0x0a, 0x07, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x46,
	0x6f, 0x72, 0x6d, 0x61, 0x74, 0x52, 0x07, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x73, 0x22, 0x44,
	0x0a, 0x0a, 0x45, 0x76, 0x69, 0x64, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x6e, 0x12, 0x20, 0x0a, 0x0b,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x6e,
	0x6f, 0x6e, 0x63, 0x65, 0x22, 0x55, 0x0a, 0x0b, 0x45, 0x76, 0x69, 0x64, 0x65, 0x6e, 0x63, 0x65,
	0x4f, 0x75, 0x74, 0x12, 0x2a, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72,
	0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x1a, 0x0a, 0x08, 0x65, 0x76, 0x69, 0x64, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x08, 0x65, 0x76, 0x69, 0x64, 0x65, 0x6e, 0x63, 0x65, 0x32, 0xe6, 0x01, 0x0a, 0x0a,
	0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x12, 0x48, 0x0a, 0x10, 0x47, 0x65,
	0x74, 0x53, 0x75, 0x62, 0x41, 0x74, 0x74, 0x65, 0x73, 0x74, 0x65, 0x72, 0x49, 0x44, 0x12, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1c, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x6f, 0x72, 0x2e, 0x53, 0x75, 0x62, 0x41, 0x74, 0x74, 0x65, 0x73, 0x74, 0x65, 0x72, 0x49,
	0x44, 0x4f, 0x75, 0x74, 0x12, 0x4e, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x53, 0x75, 0x70, 0x70, 0x6f,
	0x72, 0x74, 0x65, 0x64, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x1a, 0x1f, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72,
	0x2e, 0x53, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74,
	0x73, 0x4f, 0x75, 0x74, 0x12, 0x3e, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x45, 0x76, 0x69, 0x64, 0x65,
	0x6e, 0x63, 0x65, 0x12, 0x16, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72,
	0x2e, 0x45, 0x76, 0x69, 0x64, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x6e, 0x1a, 0x17, 0x2e, 0x63, 0x6f,
	0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x45, 0x76, 0x69, 0x64, 0x65, 0x6e, 0x63,
	0x65, 0x4f, 0x75, 0x74, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x76, 0x65, 0x72, 0x61, 0x69, 0x73, 0x6f, 0x6e, 0x2f, 0x72, 0x61, 0x74, 0x73,
	0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x6f, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_compositor_proto_rawDescOnce sync.Once
	file_compositor_proto_rawDescData = file_compositor_proto_rawDesc
)

func file_compositor_proto_rawDescGZIP() []byte {
	file_compositor_proto_rawDescOnce.Do(func() {
		file_compositor_proto_rawDescData = protoimpl.X.CompressGZIP(file_compositor_proto_rawDescData)
	})
	return file_compositor_proto_rawDescData
}

var file_compositor_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_compositor_proto_goTypes = []interface{}{
	(*Status)(nil),              // 0: compositor.Status
	(*SubAttesterID)(nil),       // 1: compositor.SubAttesterID
	(*SubAttesterIDOut)(nil),    // 2: compositor.SubAttesterIDOut
	(*Format)(nil),              // 3: compositor.Format
	(*SupportedFormatsOut)(nil), // 4: compositor.SupportedFormatsOut
	(*EvidenceIn)(nil),          // 5: compositor.EvidenceIn
	(*EvidenceOut)(nil),         // 6: compositor.EvidenceOut
	(*emptypb.Empty)(nil),       // 7: google.protobuf.Empty
}
var file_compositor_proto_depIdxs = []int32{
	0, // 0: compositor.SubAttesterIDOut.status:type_name -> compositor.Status
	1, // 1: compositor.SubAttesterIDOut.subAttesterID:type_name -> compositor.SubAttesterID
	0, // 2: compositor.SupportedFormatsOut.status:type_name -> compositor.Status
	3, // 3: compositor.SupportedFormatsOut.formats:type_name -> compositor.Format
	0, // 4: compositor.EvidenceOut.status:type_name -> compositor.Status
	7, // 5: compositor.Compositor.GetSubAttesterID:input_type -> google.protobuf.Empty
	7, // 6: compositor.Compositor.GetSupportedFormats:input_type -> google.protobuf.Empty
	5, // 7: compositor.Compositor.GetEvidence:input_type -> compositor.EvidenceIn
	2, // 8: compositor.Compositor.GetSubAttesterID:output_type -> compositor.SubAttesterIDOut
	4, // 9: compositor.Compositor.GetSupportedFormats:output_type -> compositor.SupportedFormatsOut
	6, // 10: compositor.Compositor.GetEvidence:output_type -> compositor.EvidenceOut
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_compositor_proto_init() }
func file_compositor_proto_init() {
	if File_compositor_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_compositor_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Status); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_compositor_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubAttesterID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_compositor_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubAttesterIDOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_compositor_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Format); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_compositor_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SupportedFormatsOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_compositor_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EvidenceIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_compositor_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EvidenceOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_compositor_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_compositor_proto_goTypes,
		DependencyIndexes: file_compositor_proto_depIdxs,
		MessageInfos:      file_compositor_proto_msgTypes,
	}.Build()
	File_compositor_proto = out.File
	file_compositor_proto_rawDesc = nil
	file_compositor_proto_goTypes = nil
	file_compositor_proto_depIdxs = nil
}
