# Copyright 2026 Contributors to the Veraison project.
# SPDX-License-Identifier: Apache-2.0

PLUGIN := ../../bin/nvgpu.plugin
GOPKG := github.com/veraison/ratsd/attesters/nvgpu
SRCS := main.go

include ../../../mk/plugin.mk
