# Copyright 2026 Contributors to the Veraison project.
# SPDX-License-Identifier: Apache-2.0
.DEFAULT_GOAL := test

GOPKG := github.com/veraison/ratsd/attesters/gpu
SRCS := $(wildcard *.go)

SUBDIR += plugin

include ../../mk/subdir.mk
