; See https://www.kernel.org/doc/Documentation/ABI/testing/configfs-tsm for the
; details about the semantics of the claims.

tsm-report = {
  ? auxblob: binary-string
  outblob: binary-string
  provider: tstr
  ? service-report
}

service-report = ((
  manifestblob: binary-string
  service_provider: tstr
) // service_provider: tstr)

binary-string = base64url-string .feature "json" / bstr .feature "cbor"

base64url-string = tstr .b64u bstr
