tsm-report = {
  ? auxblob: binary-string
  outblob: binary-string
  provider: binary-string
  ? service-report
}

service-report = ((
  manifestblob: binary-string
  service_provider: binary-string
) // service_provider: binary-string)

binary-string = base64url-string .feature "json" / bstr .feature "cbor"

base64url-string = tstr .b64u bstr
