tsm-report = {
  ? "auxblob": bstr
  "outblob": bstr
  "provider": bstr
  ? service-report
}
service-report //= ("manifestblob": bstr, "service_provider": bstr)
service-report //= ("service_provider": bstr)
