# Copyright 2025 Contributors to the Veraison project.
# SPDX-License-Identifier: Apache-2.0

PLUGIN := ../../bin/mocktsm.plugin
GOPKG := github.com/veraison/ratsd/attesters/mocktsm
SRCS := main.go

include ../../../mk/plugin.mk
include ../../../mk/test.mk
