//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for BadRequestErrorStatus.
const (
	N400 BadRequestErrorStatus = 400
)

// Defines values for BadRequestErrorTitle.
const (
	InvalidRequest BadRequestErrorTitle = "invalid request"
)

// Defines values for BadRequestErrorType.
const (
	TagGithubCom2024VeraisonratsdErrorInvalidrequest BadRequestErrorType = "tag:github.com,2024:veraison/ratsd:error:invalidrequest"
)

// Defines values for CMWTyp.
const (
	ApplicationvndVeraisonConfigfsTsmJson CMWTyp = "application/vnd.veraison.configfs-tsm+json"
)

// Defines values for ChaResRequestTokenVersion.
const (
	N1 ChaResRequestTokenVersion = 1
	N2 ChaResRequestTokenVersion = 2
)

// Defines values for EATEatProfile.
const (
	TagGithubCom2024Veraisonratsd EATEatProfile = "tag:github.com,2024:veraison/ratsd"
)

// Defines values for OptionDataType.
const (
	Array   OptionDataType = "array"
	Boolean OptionDataType = "boolean"
	Integer OptionDataType = "integer"
	Number  OptionDataType = "number"
	Object  OptionDataType = "object"
	String  OptionDataType = "string"
)

// Defines values for UnauthorizedErrorStatus.
const (
	N401 UnauthorizedErrorStatus = 401
)

// Defines values for UnauthorizedErrorTitle.
const (
	AccessUnauthorized UnauthorizedErrorTitle = "access unauthorized"
)

// Defines values for UnauthorizedErrorType.
const (
	TagGithubCom2024VeraisonratsdErrorUnauthorized UnauthorizedErrorType = "tag:github.com,2024:veraison/ratsd:error:unauthorized"
)

// BadRequestError defines model for BadRequestError.
type BadRequestError struct {
	Detail   *string               `json:"detail,omitempty"`
	Instance *string               `json:"instance,omitempty"`
	Status   BadRequestErrorStatus `json:"status"`
	Title    BadRequestErrorTitle  `json:"title"`
	Type     BadRequestErrorType   `json:"type"`
}

// BadRequestErrorStatus defines model for BadRequestError.Status.
type BadRequestErrorStatus float32

// BadRequestErrorTitle defines model for BadRequestError.Title.
type BadRequestErrorTitle string

// BadRequestErrorType defines model for BadRequestError.Type.
type BadRequestErrorType string

// CMW defines model for CMW.
type CMW struct {
	Typ CMWTyp `json:"typ"`
	Val string `json:"val"`
}

// CMWTyp defines model for CMW.Typ.
type CMWTyp string

// ChaResRequest defines model for ChaResRequest.
type ChaResRequest struct {
	AttesterSelection json.RawMessage            `json:"attester-selection,omitempty"`
	Nonce             string                     `json:"nonce"`
	TokenVersion      *ChaResRequestTokenVersion `json:"token-version,omitempty"`
}

// ChaResRequestTokenVersion defines model for ChaResRequest.TokenVersion.
type ChaResRequestTokenVersion int

// EAT defines model for EAT.
type EAT struct {
	EatProfile  EATEatProfile `json:"eat_profile"`
	NestedToken CMW           `json:"nested-token"`
}

// EATEatProfile defines model for EAT.EatProfile.
type EATEatProfile string

// Option defines model for Option.
type Option struct {
	DataType OptionDataType `json:"data-type"`
	Name     string         `json:"name"`
}

// OptionDataType defines model for Option.DataType.
type OptionDataType string

// SubAttester defines model for SubAttester.
type SubAttester struct {
	Name    string    `json:"name"`
	Options *[]Option `json:"options,omitempty"`
}

// UnauthorizedError defines model for UnauthorizedError.
type UnauthorizedError struct {
	Detail   *string                 `json:"detail,omitempty"`
	Instance *string                 `json:"instance,omitempty"`
	Status   UnauthorizedErrorStatus `json:"status"`
	Title    UnauthorizedErrorTitle  `json:"title"`
	Type     UnauthorizedErrorType   `json:"type"`
}

// UnauthorizedErrorStatus defines model for UnauthorizedError.Status.
type UnauthorizedErrorStatus float32

// UnauthorizedErrorTitle defines model for UnauthorizedError.Title.
type UnauthorizedErrorTitle string

// UnauthorizedErrorType defines model for UnauthorizedError.Type.
type UnauthorizedErrorType string

// ChaResRequestParametersAccept defines model for ChaResRequestParameters.accept.
type ChaResRequestParametersAccept = string

// RatsdCharesParams defines parameters for RatsdChares.
type RatsdCharesParams struct {
	Accept *ChaResRequestParametersAccept `json:"accept,omitempty"`
}

// RatsdCharesApplicationVndVeraisonCharesPlusJSONRequestBody defines body for RatsdChares for application/vnd.veraison.chares+json ContentType.
type RatsdCharesApplicationVndVeraisonCharesPlusJSONRequestBody = ChaResRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /ratsd/chares)
	RatsdChares(w http.ResponseWriter, r *http.Request, params RatsdCharesParams)

	// (GET /ratsd/subattesters)
	RatsdSubattesters(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// RatsdChares operation middleware
func (siw *ServerInterfaceWrapper) RatsdChares(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params RatsdCharesParams

	headers := r.Header

	// ------------- Optional header parameter "accept" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("accept")]; found {
		var Accept ChaResRequestParametersAccept
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "accept", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "accept", valueList[0], &Accept, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "accept", Err: err})
			return
		}

		params.Accept = &Accept

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RatsdChares(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RatsdSubattesters operation middleware
func (siw *ServerInterfaceWrapper) RatsdSubattesters(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RatsdSubattesters(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/ratsd/chares", wrapper.RatsdChares)
	m.HandleFunc("GET "+options.BaseURL+"/ratsd/subattesters", wrapper.RatsdSubattesters)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7RWT2/jthP9KgR/v9vSspMGe1DRg5MGxR4WXSQp9pANihE5triVSJUcuusG/u4FKcl/",
	"ZDlOiq1vFofke29m3vCZS1s31qAhz/Nn3oCDGgld+ndTwh36O/wzoKdP26UMpMSGYoQ2POclgkLHBTdQ",
	"I895tyy4lyXWEONo3cQVT06bJd9sNv1iuucaVHfJrXPWJSDONuhIYwpQSKCrkYME18YTGImji56AQjoB",
	"Tah5/ng1mz2JPs6EukAX40hThXthXJsVVFox18Liu027w9sPuz0Ey3ypqQxFJm0tLmeXV/kKHWhvzdQB",
	"eZVjpJd3h58+eyN4XNQOVTo4rvYgt6R222zxFSVFSDcfPx+LR+tmHyY0TaUlkLZmujIq6yFm0pqFXi78",
	"hHz97qu3ZpT1ClIeFtbVQDznBXh8fxVcxV9Bg7f7R6Hv19oxCSBCT+gmHiuUEfwBigR3CEDwbxNba8K6",
	"oTXPyQXcCG5sVy2voSA42T/QTFbofHenwgWEinh+IXpNL8TljpI2hMtYVgP67b1ijMmYHrfzh2MVEOj3",
	"xtmFrt5YeaOpNBGHmiSG8bj/O1zwnP9vuvOEadel01hZQ0b7aAanjTH6tenTNmhuIJgMm2mbwq5JxVZX",
	"wQtrK4SYb3AO1lz0l4ySTJ70fKY2U5TYgzJG4D4U8y55xyxO3CO4TbRTTCxFf07pTqatwXQkRxGPofzN",
	"QKDSOv03qv/eTi9eZadxInjPwh6072upZ07+l4YaKaMMTtP6PmanVe8awaGbByrjv5S2uKlIn3cWUhI1",
	"7aTTZmGTnq0s/G7+cM9uV1qhkchubNX5APsZsLaGzT99iEbZWw6fZbPsoi0lNNBonvMfslk244I3QGUC",
	"1aoxlSW4FmVjWxtV6KXTXetFl60qNEtkDn1jjcd4W8bmaWR7BkxuI8AowUJjDfMh5U+wJRp0QOgZlciw",
	"p6ANu50/sL+m7ObjZ9b6asYTXpcGzQcVaUeENy1AcfDSeBzviF3I9MxLZPPUJhg9XVu1jrylNYQmSXB6",
	"4iUw7azrUwlnnfBgUG0Oa6ubMb24KROXs9kLgBBoEqR/JwvrfmR7lvrTl5Hyfz8o/+nq8gs/xL4ba9qA",
	"W4+O5TEAUYXzAIb9N7z9JeXiSEt6HdbkQ4n9O4uV4NtqQ4UqizV/9aJ6jbNFhfUbUzh8b54A5dGt0DFp",
	"Q6WYscSCUeiiP6pU/z1oFZCRZf2b0a8NwbcO/MV3B3/s7yPw563h6kPPzQ4sLfXdvpk9Pm2eYkBXWj4U",
	"/Vsl1fESRwzlFyQGrNKemF0kVXwoJtt9DFagKygqZNYwKrVnNchSGzzhD/f7l76pkQ46e3vGiLivmsL7",
	"s/54FL+phtPvnwAAAP//8agf4mkNAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
