//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes bearerAuthContextKey = "BearerAuth.Scopes"
)

// Defines values for BadRequestErrorStatus.
const (
	N400 BadRequestErrorStatus = 400
)

// Valid indicates whether the value is a known member of the BadRequestErrorStatus enum.
func (e BadRequestErrorStatus) Valid() bool {
	switch e {
	case N400:
		return true
	default:
		return false
	}
}

// Defines values for BadRequestErrorTitle.
const (
	InvalidRequest BadRequestErrorTitle = "invalid request"
)

// Valid indicates whether the value is a known member of the BadRequestErrorTitle enum.
func (e BadRequestErrorTitle) Valid() bool {
	switch e {
	case InvalidRequest:
		return true
	default:
		return false
	}
}

// Defines values for BadRequestErrorType.
const (
	TagGithubCom2024VeraisonratsdErrorInvalidrequest BadRequestErrorType = "tag:github.com,2024:veraison/ratsd:error:invalidrequest"
)

// Valid indicates whether the value is a known member of the BadRequestErrorType enum.
func (e BadRequestErrorType) Valid() bool {
	switch e {
	case TagGithubCom2024VeraisonratsdErrorInvalidrequest:
		return true
	default:
		return false
	}
}

// Defines values for CMWTyp.
const (
	ApplicationvndVeraisonTsmReportCbor CMWTyp = "application/vnd.veraison.tsm-report+cbor"
	ApplicationvndVeraisonTsmReportJson CMWTyp = "application/vnd.veraison.tsm-report+json"
)

// Valid indicates whether the value is a known member of the CMWTyp enum.
func (e CMWTyp) Valid() bool {
	switch e {
	case ApplicationvndVeraisonTsmReportCbor:
		return true
	case ApplicationvndVeraisonTsmReportJson:
		return true
	default:
		return false
	}
}

// Defines values for EATEatProfile.
const (
	TagGithubCom2024Veraisonratsd EATEatProfile = "tag:github.com,2024:veraison/ratsd"
)

// Valid indicates whether the value is a known member of the EATEatProfile enum.
func (e EATEatProfile) Valid() bool {
	switch e {
	case TagGithubCom2024Veraisonratsd:
		return true
	default:
		return false
	}
}

// Defines values for OptionDataType.
const (
	Array   OptionDataType = "array"
	Boolean OptionDataType = "boolean"
	Integer OptionDataType = "integer"
	Number  OptionDataType = "number"
	Object  OptionDataType = "object"
	String  OptionDataType = "string"
)

// Valid indicates whether the value is a known member of the OptionDataType enum.
func (e OptionDataType) Valid() bool {
	switch e {
	case Array:
		return true
	case Boolean:
		return true
	case Integer:
		return true
	case Number:
		return true
	case Object:
		return true
	case String:
		return true
	default:
		return false
	}
}

// Defines values for UnauthorizedErrorStatus.
const (
	N401 UnauthorizedErrorStatus = 401
)

// Valid indicates whether the value is a known member of the UnauthorizedErrorStatus enum.
func (e UnauthorizedErrorStatus) Valid() bool {
	switch e {
	case N401:
		return true
	default:
		return false
	}
}

// Defines values for UnauthorizedErrorTitle.
const (
	AccessUnauthorized UnauthorizedErrorTitle = "access unauthorized"
)

// Valid indicates whether the value is a known member of the UnauthorizedErrorTitle enum.
func (e UnauthorizedErrorTitle) Valid() bool {
	switch e {
	case AccessUnauthorized:
		return true
	default:
		return false
	}
}

// Defines values for UnauthorizedErrorType.
const (
	TagGithubCom2024VeraisonratsdErrorUnauthorized UnauthorizedErrorType = "tag:github.com,2024:veraison/ratsd:error:unauthorized"
)

// Valid indicates whether the value is a known member of the UnauthorizedErrorType enum.
func (e UnauthorizedErrorType) Valid() bool {
	switch e {
	case TagGithubCom2024VeraisonratsdErrorUnauthorized:
		return true
	default:
		return false
	}
}

// BadRequestError defines model for BadRequestError.
type BadRequestError struct {
	Detail   *string               `json:"detail,omitempty"`
	Instance *string               `json:"instance,omitempty"`
	Status   BadRequestErrorStatus `json:"status"`
	Title    BadRequestErrorTitle  `json:"title"`
	Type     BadRequestErrorType   `json:"type"`
}

// BadRequestErrorStatus defines model for BadRequestError.Status.
type BadRequestErrorStatus float32

// BadRequestErrorTitle defines model for BadRequestError.Title.
type BadRequestErrorTitle string

// BadRequestErrorType defines model for BadRequestError.Type.
type BadRequestErrorType string

// CMW defines model for CMW.
type CMW struct {
	Typ CMWTyp `json:"typ"`
	Val string `json:"val"`
}

// CMWTyp defines model for CMW.Typ.
type CMWTyp string

// ChaResRequest defines model for ChaResRequest.
type ChaResRequest struct {
	AttesterSelection    *[]string                    `json:"attester-selection,omitempty"`
	Nonce                string                       `json:"nonce"`
	AdditionalProperties map[string]map[string]string `json:"-"`
}

// EAT defines model for EAT.
type EAT struct {
	EatProfile  EATEatProfile `json:"eat_profile"`
	NestedToken CMW           `json:"nested-token"`
}

// EATEatProfile defines model for EAT.EatProfile.
type EATEatProfile string

// Option defines model for Option.
type Option struct {
	DataType OptionDataType `json:"data-type"`
	Name     string         `json:"name"`
}

// OptionDataType defines model for Option.DataType.
type OptionDataType string

// SubAttester defines model for SubAttester.
type SubAttester struct {
	Name    string    `json:"name"`
	Options *[]Option `json:"options,omitempty"`
}

// UnauthorizedError defines model for UnauthorizedError.
type UnauthorizedError struct {
	Detail   *string                 `json:"detail,omitempty"`
	Instance *string                 `json:"instance,omitempty"`
	Status   UnauthorizedErrorStatus `json:"status"`
	Title    UnauthorizedErrorTitle  `json:"title"`
	Type     UnauthorizedErrorType   `json:"type"`
}

// UnauthorizedErrorStatus defines model for UnauthorizedError.Status.
type UnauthorizedErrorStatus float32

// UnauthorizedErrorTitle defines model for UnauthorizedError.Title.
type UnauthorizedErrorTitle string

// UnauthorizedErrorType defines model for UnauthorizedError.Type.
type UnauthorizedErrorType string

// ChaResRequestParametersAccept defines model for ChaResRequestParameters.accept.
type ChaResRequestParametersAccept = string

// bearerAuthContextKey is the context key for BearerAuth security scheme
type bearerAuthContextKey string

// RatsdCharesParams defines parameters for RatsdChares.
type RatsdCharesParams struct {
	Accept *ChaResRequestParametersAccept `json:"accept,omitempty"`
}

// RatsdCharesApplicationVndVeraisonCharesPlusJSONRequestBody defines body for RatsdChares for application/vnd.veraison.chares+json ContentType.
type RatsdCharesApplicationVndVeraisonCharesPlusJSONRequestBody = ChaResRequest

// Getter for additional properties for ChaResRequest. Returns the specified
// element and whether it was found
func (a ChaResRequest) Get(fieldName string) (value map[string]string, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ChaResRequest
func (a *ChaResRequest) Set(fieldName string, value map[string]string) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]map[string]string)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ChaResRequest to handle AdditionalProperties
func (a *ChaResRequest) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["attester-selection"]; found {
		err = json.Unmarshal(raw, &a.AttesterSelection)
		if err != nil {
			return fmt.Errorf("error reading 'attester-selection': %w", err)
		}
		delete(object, "attester-selection")
	}

	if raw, found := object["nonce"]; found {
		err = json.Unmarshal(raw, &a.Nonce)
		if err != nil {
			return fmt.Errorf("error reading 'nonce': %w", err)
		}
		delete(object, "nonce")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]map[string]string)
		for fieldName, fieldBuf := range object {
			var fieldVal map[string]string
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ChaResRequest to handle AdditionalProperties
func (a ChaResRequest) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.AttesterSelection != nil {
		object["attester-selection"], err = json.Marshal(a.AttesterSelection)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'attester-selection': %w", err)
		}
	}

	object["nonce"], err = json.Marshal(a.Nonce)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'nonce': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /ratsd/chares)
	RatsdChares(w http.ResponseWriter, r *http.Request, params RatsdCharesParams)

	// (GET /ratsd/subattesters)
	RatsdSubattesters(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// RatsdChares operation middleware
func (siw *ServerInterfaceWrapper) RatsdChares(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params RatsdCharesParams

	headers := r.Header

	// ------------- Optional header parameter "accept" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("accept")]; found {
		var Accept ChaResRequestParametersAccept
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "accept", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "accept", valueList[0], &Accept, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "accept", Err: err})
			return
		}

		params.Accept = &Accept

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RatsdChares(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RatsdSubattesters operation middleware
func (siw *ServerInterfaceWrapper) RatsdSubattesters(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RatsdSubattesters(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/ratsd/chares", wrapper.RatsdChares)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/ratsd/subattesters", wrapper.RatsdSubattesters)

	return m
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"tFbfb+M2DP5XBG1vc5y0K+7Bhz2kXTHcw2FF2+EeesVAS2ysmy15FJ1eVuR/HyTbjZ06/XG461NjUeTH",
	"j+RHPUjlqtpZtOxl9iBrIKiQkeKvswIu0V/ivw16vng8SkEprDlYGCszWSBoJJlICxXKTHbHifSqwAqC",
	"HW/qcOKZjF3J7XbbH8Y4p6C7IOdEjiIQcjUSG4wGGhlMOeEokcZ6Bqtw8tAzcBM9oG0qmd2cLBa3SW9n",
	"mypHCnZsuMSBmTR2DaXRglpYcndp57z9sLvDsMpWhosmT5WrkuPF8Um2RgLjnZ0TsNcZhvSyzvlh39tE",
	"hkNDqKPjcNqDfExqd83lX1BxgHT28dNT8nhTD2FCXZdGARtn52ur0x5iyr6aEdaO+Jcv3lmZvMpU5Y4m",
	"6VlDLNidowpYZjIHj+9OGirlK/KV7f3JHIdNGSKA1iZAhPJilPeh7wcKOQgx5g+Y0TPSzGOJKniMnc9Y",
	"PesOiGAjE/l15qpgXPNGZkwNbhNpXdex38BOe3eKmfPl9dPqI/DfNbk7U76xWSeLagMTesbuH4ws/Ex4",
	"JzP503wnI/NusOehGffBD9HseZvK6M+6p3tPD4Bhtj9/Hcqkn+ugDYyr+F/uXIkQe7orSxdkMskoYw8v",
	"1SFYJQMoUwlcNfmya5+nWRyIk0gX0/ajNnuO6Y6m/d6bRDyF8i8LDReOzH+of7wCH71KgcMS8V40A2jf",
	"V4Vf8PyNGhxSRtWQ4c1VqE7L3ikCIS0bLsKvWLZwKY+fdxNfMNftcjT2zkU+W1rk5fL6SpyvjUarUJy5",
	"slMi8Ttg5axYXnwIkonk47zIRbpIj9pWQgu1kZn8NV2kC5nIGriIoFo25qoAalHWrhVUjV6R6UYv6G1Z",
	"ol2hIPS1sx5DtFQs45b3AoR6tACrE9HUzgrfxPolYoUWCRi94AIF9ikYK86X1+J+Ls4+fhKtDKYy4qW4",
	"cD7okHZAeNYCTEaPk5vpidiZzF94vGxv2wKj51OnNyFv5SyjbXfKoc3XstUuyL6U8KISjlbWdtxb3Uro",
	"yY2VOF4sngGkqvu4dt8LVd0r/u3zRNO/22v6+fr4sxwj3u0eY4E2k4tnGBaBZ41qc38vBko+CWB/6vaj",
	"P8dXWGSRpXEnXhfYP8hEAb7tMdSo09DpJ89yVpPLS6zeWLj9h+kBUB5pjSSUa0otrGPRWI0UVFHHru9B",
	"6wYFO9E/Lv3GMnztwB99d/BPVX0C/rKVWTNW2nQkZHHahhJ2c7u9DQZda/km799IsXtXOCEjfyALEKXx",
	"LNxdZMU3+ezxnoA1mBLyEoWzggvjRQWqMBYPqMLVMOibxmc0z48+Jsh91e4dbvinC/hNPRz//g8AAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
