# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.0'

    - name: Install Protoc
      uses: arduino/setup-protoc@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        version: "27.2"

    - name: Install protoc-gen-go
      run: go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.31.0

    - name: Install protoc-gen-go-grpc
      run: go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

    - name: Install mockgen
      run: go install go.uber.org/mock/mockgen@latest

    - name: Generate protobufs and ratsd server
      run: go generate ./...

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
